version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=wapi
      - POSTGRES_USER=wapi
      - POSTGRES_PASSWORD=wapi
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./scripts/db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local